#!/bin/sh

keyboard () {
    t=$(xset -q | grep LED)
    code=${t##*mask:  }


    if [[ $code -eq "00000002" ]]; then
            result="EN"
    else
            result="RU"
    fi
printf "%s %s \\n" "$result"
}

keyboard
